# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  heroku: circleci/heroku@0.0.10
  puppeteer: threetreeslight/puppeteer@0.1.2 # Need to enable 3rd party
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:latest-browsers

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run : npm install && sudo apt-get update
      
      # - run:
      #     name: "Creating ENV file"
      #     command: |
      #       npm install && sudo apt-get update && echo ${MONGO_USER} && echo ${MONGO_PASSWORD} && echo ${MONGO_URI} && ls -la
      #       touch ./.env
      #       echo MONGO_USER=${MONGO_USER} >> ./.env
      #       echo MONGO_PASSWORD=${MONGO_PASSWORD} >> ./.env
      #       echo MONGO_URI=${MONGO_URI} >> ./.env
      #       ls -la
      #       cat ./.env

      - puppeteer/install
      # - run:
      #     name: Install puppeteer dependencies
      #     command: sudo apt-get update && sudo apt-get install -y libxtst6 libnss3 libnspr4 libxss1 libasound2
      #       libatk-bridge2.0-0 libgtk-3-0 libgdk-pixbuf2.0-0

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # # run tests!
      # - run: npm test
  deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/install
      - run:
          name: "Setting ENV for HEROKU"
          command: |
            heroku config:set MONGO_USER=${MONGO_USER} MONGO_PASSWORD=${MONGO_PASSWORD} MONGO_URI=${MONGO_URI} DOMAIN_URL=${DOMAIN_URL} -a ${HEROKU_APP_NAME}
      - heroku/deploy-via-git:
          only-branch: master

workflows:
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master